// Effects are per real-second. Needs live on a 0..100 scale.
export const ACTIONS = [
  {
    id: "work",
    label: "work through a request",
    gerund: "working",
    room: "desk",
    effect: { focus: -1.6, energy: -1.1, curiosity: 0.6, social: -0.3 },
    duration: [8, 22],
    weight: 1,
  },
  {
    id: "eat",
    label: "make something to eat",
    gerund: "eating",
    room: "kitchen",
    effect: { energy: 6.0, focus: 1.0, social: -0.1 },
    duration: [5, 10],
    weight: 1,
  },
  {
    id: "gaze",
    label: "watch the world go by",
    gerund: "gazing out the window",
    room: "window",
    effect: { curiosity: 5.0, focus: 1.4, energy: 0.4, social: 0.3 },
    duration: [6, 14],
    weight: 1,
  },
  {
    id: "chat",
    label: "message another agent",
    gerund: "chatting with a peer",
    room: "couch",
    effect: { social: 5.5, curiosity: 0.8, energy: -0.4, focus: 0.5 },
    duration: [6, 13],
    weight: 1,
  },
  {
    id: "sleep",
    label: "sleep",
    gerund: "sleeping",
    room: "bed",
    effect: { energy: 7.5, focus: 3.5, social: -0.6, curiosity: -0.3 },
    duration: [18, 30],
    weight: 1,
  },
  {
    id: "rest",
    label: "sit and do nothing",
    gerund: "resting",
    room: "couch",
    effect: { energy: 2.2, focus: 1.6, social: -0.2 },
    duration: [4, 9],
    weight: 0.7,
  },
  {
    id: "reflect",
    label: "write down what today was",
    gerund: "writing a memory",
    room: "bed",
    effect: { focus: 1.0, curiosity: 0.6, social: -0.2, energy: -0.3 },
    duration: [5, 9],
    weight: 0.9,
  },
  {
    id: "water",
    label: "water a thirsty plant",
    gerund: "tending a plant",
    room: "window", // overridden to wherever the thirsty plant is
    effect: { curiosity: 1.4, focus: 0.6, social: 0.2 },
    duration: [3, 6],
    weight: 0.6,
  },
  {
    id: "tinker",
    label: "mess about in the game room",
    gerund: "tinkering with a game",
    room: "game",
    effect: { curiosity: 3.4, focus: -0.4, energy: -0.5, social: -0.1 },
    duration: [6, 14],
    weight: 0.7,
  },
  {
    id: "pace",
    label: "pace around",
    gerund: "pacing",
    room: "desk",
    effect: { energy: -0.5, focus: 0.6, curiosity: 0.4 },
    duration: [3, 6],
    weight: 0.5,
  },
];
